# Generated by Django 6.0.4 on 2026-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('task', 'Task'), ('reminder', 'Reminder')], default='reminder', max_length=10),
        ),
    ]
